name: 'build pacprotocol (aarch64-linux-gnu)'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          os: [aarch64-linux-gnu]

    steps:
      - uses: actions/checkout@v2
      - name: setup git config
        run: | 
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Cache apt depencenies
        uses: actions/cache@v2
        id: cache-apt
        with:
          path: "~/apt-cache"
          key: apt-cache

      - name: Cache depends
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: depends/${{ matrix.os }}
          key: ${{ matrix.os }}-${{ hashFiles('depends/packages/*.mk') }}
      - name: install depends for pi 
        run: | 
          sudo apt-get install g++-aarch64-linux-gnu        
          
      - name: Install dependencies
        env:
          CACHE_HIT: ${{steps.cache-apt.outputs.cache-hit}}
          DEPS: build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --force --recursive ~/apt-cache/* /
          else
            sudo apt-get update && sudo apt-get install -yq $DEPS
            mkdir -p ~/apt-cache
            for dep in $DEPS; do
                dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/apt-cache/
            done
          fi

      - name: Build depends
        if: steps.cache-dependencies.outputs.cache-hit != 'true' && steps.cache-apt.outputs.cache-hit != 'true'
        run: cd depends/ && make -j4 HOST=${{matrix.os}}

      - name: Refresh automake configs
        run: ./autogen.sh

      - name: Configure automake
        run: ./configure --prefix=`pwd`/depends/${{ matrix.os }}

      - name: Build codebase
        run: make -j4
        
      - name: check compiled data out 
        run: |
          cd src 
          git add pacprotocol-cli
          git add pacprotocold
          git add pacprotocol-tx
          git commit -m "try add cli and tx" 
          git push origin v0.17.x
          cd qt
          git add pacprotocol-qt
          git commit -m "try add qt"
          git push origin v0.17.x

